services:
  tictactoe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tictactoe
    ports:
      - "5900:5900"
    environment:
      VNC_PASS: "StrongPass123"
      SCREEN_GEOMETRY: "1280x720x24"
    restart: "unless-stopped"
